- name: Create an instance
  hosts: localhost
  vars:
      gcp_project: project-name
      gcp_cred_kind: serviceaccount
      gcp_cred_file: ./service_account_credentials.json
      zone: "europe-west1-b"
      region: "europe-west1"

  tasks:
   - name: create a disk
     gcp_compute_disk:
         name: 'disk-vm'
         size_gb: 20
         source_image: 'projects/confidential-vm-images/global/images/ubuntu-2004-focal-v20210927'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: disk

   - name: create a address
     gcp_compute_address:
         name: 'address-vm'
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: address

   - name: create a instance
     gcp_compute_instance:
         state: present
         name: vm
         machine_type: e2-medium
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
         network_interfaces:
             - network: null # use default
               access_configs:
                 - name: 'External NAT'
                   nat_ip: "{{ address }}"
                   type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
     register: instance

   - name: Wait for SSH to come up
     wait_for: host={{ address.address }} port=22 delay=10 timeout=60