---
- name: Destroy K8s Network, Cluster and Node Pool
  hosts: localhost
  gather_facts: false
  environment:
    GOOGLE_CREDENTIALS: "{{ credentials_file }}"   
  roles:
    - destroy_k8s
    - destroy_network