- name: Destroy K8s Cluster  
  google.cloud.gcp_container_cluster:    
    name: "{{ cluster_name }}"    
    location: "{{ zone }}"    
    project: "{{ project_id }}"    
    auth_kind: serviceaccount    
    service_account_file: "{{ credentials_file }}"    
    state: absent